set -ex

docker exec -i webp-idz-postgres psql --username=postgres << EOF
DROP DATABASE IF EXISTS webp_idz_db;

CREATE DATABASE webp_idz_db;
EOF

docker exec -i webp-idz-postgres psql --username=postgres --dbname=webp_idz_db << EOF
CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL UNIQUE CHECK (TRIM(name) <> '')
);

CREATE TABLE ticket_statuses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL CHECK (TRIM(name) <> ''),
    "order" INTEGER NOT NULL CHECK("order" >= 0),
    project_id INTEGER NOT NULL REFERENCES projects (id),
    UNIQUE ("order", project_id) DEFERRABLE INITIALLY DEFERRED, -- necessary for editing order
    UNIQUE (name, project_id)
);

CREATE TABLE tickets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL CHECK (TRIM(name) <> ''),
    description TEXT NOT NULL,
    status_id INTEGER NOT NULL REFERENCES ticket_statuses (id),
    project_id INTEGER NOT NULL REFERENCES projects (id),
    UNIQUE (name, project_id)
);
EOF
